spring:
  application:
    name: user-service
  cloud:
    consul:
      enabled: false
      discovery:
        enabled: false

  datasource:
    url: jdbc:h2:mem:user-db
   # jdbc:mysql://localhost:3306/blog-marc
    driver-class-name: org.h2.Driver
    username: marc
    password: marc
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true
      path: /h2-console

#    username: root
#    password: marc
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect

server:
  port: 8090

